CREATE TABLE CourseCatelog (
	District VARCHAR(10),
	College VARCHAR(6),
	"Course ID" VARCHAR(12),
	"Control Number" VARCHAR(12),
	"Course Title" VARCHAR(68),
	"Sections Count" INTEGER,
	"TOP Code" VARCHAR(85),
	"Credit Status" VARCHAR(75),
	"Transfer Status" VARCHAR(75),
	"Maximum Units" INTEGER,
	"Minimum Units" INTEGER,
	"Basic Skills Status" VARCHAR(75),
	"SAM Status" VARCHAR(75),
	"Prior To Transfer Status" VARCHAR(75),
	"Non-Credit Category" VARCHAR(75),
	"General Education Status" VARCHAR(1),
	"Support Status" VARCHAR(75),
	Term VARCHAR(11)
);
